//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteHopDongVay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HDV_GNN
    {
        public string GNN_SO { get; set; }
        public System.DateTime GNN_NGAY { get; set; }
        public string KUGN_SO { get; set; }
        public string MSLNT { get; set; }
        public decimal TYGIA { get; set; }
        public decimal TIENVAY { get; set; }
        public decimal TIENVAYVND { get; set; }
        public decimal TIENMAT { get; set; }
        public decimal CKHOAN { get; set; }
    }
}
