//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteHopDongVay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HDV_VAY3
    {
        public string HD_SO { get; set; }
        public string STK_SO { get; set; }
        public System.DateTime STK_NGAY { get; set; }
        public decimal STK_TRIGIA { get; set; }
        public decimal STK_LS { get; set; }
        public System.DateTime STK_NDH { get; set; }
        public string STK_MSNH { get; set; }
        public string STK_NSH { get; set; }
    }
}
