//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteHopDongVay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HDV_KUGN1
    {
        public string KUGN_SO { get; set; }
        public System.DateTime KUGN_NGAY { get; set; }
        public string HD_SO { get; set; }
        public string MSLNT { get; set; }
        public decimal TIENVAY { get; set; }
        public decimal TIENVAYVND { get; set; }
        public decimal TIENMAT { get; set; }
        public decimal CKHOAN { get; set; }
        public string MDSD { get; set; }
        public string CTKT { get; set; }
        public int SOTHANGVAY { get; set; }
        public int TLVCN { get; set; }
        public int TLVCN_TQN { get; set; }
        public System.DateTime NTNGOC { get; set; }
        public int TTNGOC { get; set; }
        public decimal TL_LS { get; set; }
        public decimal TL_LS_TQN { get; set; }
        public decimal TL_LSGH { get; set; }
    }
}
