//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteHopDongVay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HDV_VAY1
    {
        public string HD_SO { get; set; }
        public System.DateTime HD_NGAY { get; set; }
        public string MSNH { get; set; }
        public string MSLNT { get; set; }
        public decimal TIENVAY { get; set; }
        public decimal TYGIA { get; set; }
        public System.DateTime RVTUNGAY { get; set; }
        public System.DateTime RVDENNGAY { get; set; }
        public int SOTHANGVAY { get; set; }
        public int KYHANTRANO { get; set; }
        public int HANTDLS { get; set; }
        public decimal TL_LS { get; set; }
        public decimal TL_LSQH { get; set; }
        public int LSTHEO { get; set; }
        public int TTGTHEO { get; set; }
        public Nullable<bool> TC_TSCD { get; set; }
        public Nullable<bool> TC_STK { get; set; }
        public Nullable<bool> TC_KHAC { get; set; }
        public string TC_HD_SO { get; set; }
        public System.DateTime TC_HD_NGAY { get; set; }
        public string STK_SO { get; set; }
        public Nullable<System.DateTime> STK_NGAY { get; set; }
        public Nullable<decimal> STK_TRIGIA { get; set; }
        public Nullable<decimal> STK_LS { get; set; }
        public Nullable<System.DateTime> STK_NDH { get; set; }
        public string STK_MSNH { get; set; }
        public string STK_NSH { get; set; }
    }
}
