//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteHopDongVay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HDV_GBNLV
    {
        public string GBNLV_SO { get; set; }
        public System.DateTime GBNLV_NGAY { get; set; }
        public string KUGN_SO { get; set; }
        public string MSLNT { get; set; }
        public decimal TYGIA { get; set; }
        public decimal TIENLAI { get; set; }
        public decimal TIENLAIND { get; set; }
    }
}
