//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteHopDongVay.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbQuanLyHopDongVayEntities : DbContext
    {
        public dbQuanLyHopDongVayEntities()
            : base("name=dbQuanLyHopDongVayEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<HDV_GBNLV> HDV_GBNLV { get; set; }
        public virtual DbSet<HDV_GBNNG> HDV_GBNNG { get; set; }
        public virtual DbSet<HDV_GNN> HDV_GNN { get; set; }
        public virtual DbSet<HDV_KUGN1> HDV_KUGN1 { get; set; }
        public virtual DbSet<HDV_KUGN2> HDV_KUGN2 { get; set; }
        public virtual DbSet<HDV_VAY1> HDV_VAY1 { get; set; }
        public virtual DbSet<HDV_VAY2> HDV_VAY2 { get; set; }
        public virtual DbSet<HDV_VAY3> HDV_VAY3 { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
